version: '3.7'
services:
  planetscale:
    container_name: planetscale
    # ports:
    #   - '3306:3306'
    image: planetscale/pscale:latest
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SHADOW_DB: ${SHADOW_DB}
    volumes:
      - mysql:/var/lib/mysql
  prisma:
    links:
      - planetscale
    depends_on:
      - planetscale
    container_name: prisma
    ports:
      - '5555:5555'
    build:
      context: backend/prisma
      dockerfile: Dockerfile
    volumes:
      - /app/prisma
  backend:
    links:
      - planetscale
    depends_on:
      - planetscale
    container_name: backend
    ports:
      - '4000:4000'
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - /app/node_modules
      - /app/prisma
  frontend:
    container_name: frontend
    ports:
      - '3000:3000'
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next

volumes: #define our mysql volume used above
  mysql: