// Generated by https://quicktype.io

export interface AllPolicies {
  data: Data;
}

export interface Data {
  allPolicies: AllPolicy[];
  policiesCount: number;
}

export interface AllPolicy {
  provider: string;
  customer: Customer;
  insuranceType: string;
  status: string;
  policyNumber: number;
  startDate: string;
  endDate: string;
  createdAt: string;
}

export interface Customer {
  firstName: string;
  lastName: string;
  dateOfBirth: string;
}
