// Generated by https://quicktype.io

export interface PolicyEnum {
  __type: Type;
}

interface Type {
  enumValues: EnumValue[];
}

export interface EnumValue {
  name: PolicyStatus;
}

export enum PolicyStatus {
  ACTIVE = "ACTIVE",
  CANCELLED = "CANCELLED",
  PENDING = "PENDING",
  DROPPED_OUT = "DROPPED_OUT",
}
